; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=pre-isel-intrinsic-lowering -mtriple aarch64-unknown-linux -S < %s | FileCheck --check-prefix=NOPAUTH %s
; RUN: opt -passes=pre-isel-intrinsic-lowering -mtriple aarch64-unknown-linux -mattr=+pauth -S < %s | FileCheck --check-prefix=PAUTH1 %s
; RUN: opt -passes=pre-isel-intrinsic-lowering -mtriple arm64e-apple-darwin -S < %s | FileCheck --check-prefix=PAUTH2 %s

@ds = external global i8

define ptr @sign1(ptr %p) {
; NOPAUTH-LABEL: define ptr @sign1(
; NOPAUTH-SAME: ptr [[P:%.*]]) {
; NOPAUTH-NEXT:    [[TMP1:%.*]] = call ptr @__emupac_autda(ptr [[P]], i64 1)
; NOPAUTH-NEXT:    ret ptr [[TMP1]]
;
; PAUTH1-LABEL: define ptr @sign1(
; PAUTH1-SAME: ptr [[P:%.*]]) #[[ATTR0:[0-9]+]] {
; PAUTH1-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[P]]) [ "ptrauth"(i64 2, i64 1, i64 0) ]
; PAUTH1-NEXT:    ret ptr [[SIGNED]]
;
; PAUTH2-LABEL: define ptr @sign1(
; PAUTH2-SAME: ptr [[P:%.*]]) {
; PAUTH2-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[P]]) [ "ptrauth"(i64 2, i64 1, i64 0) ]
; PAUTH2-NEXT:    ret ptr [[SIGNED]]
;
  %signed = call ptr @llvm.ptrauth.auth.p0(ptr %p, i32 2, i64 1)
  ret ptr %signed
}
define ptr @sign2(ptr %p) {
; NOPAUTH-LABEL: define ptr @sign2(
; NOPAUTH-SAME: ptr [[P:%.*]]) {
; NOPAUTH-NEXT:    [[TMP1:%.*]] = call ptr @__emupac_autda(ptr [[P]], i64 1) [ "deactivation-symbol"(ptr @ds) ]
; NOPAUTH-NEXT:    ret ptr [[TMP1]]
;
; PAUTH1-LABEL: define ptr @sign2(
; PAUTH1-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
; PAUTH1-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[P]]) [ "ptrauth"(i64 2, i64 1, i64 0), "deactivation-symbol"(ptr @ds) ]
; PAUTH1-NEXT:    ret ptr [[SIGNED]]
;
; PAUTH2-LABEL: define ptr @sign2(
; PAUTH2-SAME: ptr [[P:%.*]]) {
; PAUTH2-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[P]]) [ "ptrauth"(i64 2, i64 1, i64 0), "deactivation-symbol"(ptr @ds) ]
; PAUTH2-NEXT:    ret ptr [[SIGNED]]
;
  %signed = call ptr @llvm.ptrauth.auth.p0(ptr %p, i32 2, i64 1) [ "deactivation-symbol"(ptr @ds) ]
  ret ptr %signed
}
define ptr @sign3(ptr %p) {
; NOPAUTH-LABEL: define ptr @sign3(
; NOPAUTH-SAME: ptr [[P:%.*]]) {
; NOPAUTH-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[P]]) [ "ptrauth"(i64 0, i64 1, i64 0), "deactivation-symbol"(ptr @ds) ]
; NOPAUTH-NEXT:    ret ptr [[SIGNED]]
;
; PAUTH1-LABEL: define ptr @sign3(
; PAUTH1-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
; PAUTH1-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[P]]) [ "ptrauth"(i64 0, i64 1, i64 0), "deactivation-symbol"(ptr @ds) ]
; PAUTH1-NEXT:    ret ptr [[SIGNED]]
;
; PAUTH2-LABEL: define ptr @sign3(
; PAUTH2-SAME: ptr [[P:%.*]]) {
; PAUTH2-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[P]]) [ "ptrauth"(i64 0, i64 1, i64 0), "deactivation-symbol"(ptr @ds) ]
; PAUTH2-NEXT:    ret ptr [[SIGNED]]
;
  %signed = call ptr @llvm.ptrauth.auth.p0(ptr %p, i32 0, i64 1) [ "deactivation-symbol"(ptr @ds) ]
  ret ptr %signed
}
