; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -S | FileCheck %s

@ds = external global i8

define void @test_ptrauth_sign(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_sign(
; CHECK-NEXT:    [[ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 0, i64 0) ]
; CHECK-NEXT:    [[IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P]]) [ "ptrauth"(i64 1, i64 42, i64 0) ]
; CHECK-NEXT:    [[ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]) ]
; CHECK-NEXT:    [[BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %zero.discr    = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 0)
  %imm.discr     = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 42)
  %addr.discr    = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 %addr)
  %blended.discr = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 %tmp)
  ret void
}

define void @test_ptrauth_sign_ds(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_sign_ds(
; CHECK-NEXT:    [[ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 0, i64 0), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    [[IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P]]) [ "ptrauth"(i64 1, i64 42, i64 0), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    [[ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    [[BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR]]), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %zero.discr    = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 0) [ "deactivation-symbol"(ptr @ds) ]
  %imm.discr     = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 42) [ "deactivation-symbol"(ptr @ds) ]
  %addr.discr    = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 %addr) [ "deactivation-symbol"(ptr @ds) ]
  %blended.discr = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 %tmp) [ "deactivation-symbol"(ptr @ds) ]
  ret void
}

define void @test_ptrauth_auth(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_auth(
; CHECK-NEXT:    [[ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 0, i64 0) ]
; CHECK-NEXT:    [[IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]]) [ "ptrauth"(i64 1, i64 42, i64 0) ]
; CHECK-NEXT:    [[ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]) ]
; CHECK-NEXT:    [[BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %zero.discr    = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 0)
  %imm.discr     = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 42)
  %addr.discr    = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 %addr)
  %blended.discr = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 %tmp)
  ret void
}

define void @test_ptrauth_auth_ds(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_auth_ds(
; CHECK-NEXT:    [[ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 0, i64 0), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    [[IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]]) [ "ptrauth"(i64 1, i64 42, i64 0), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    [[ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    [[BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR]]), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %zero.discr    = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 0) [ "deactivation-symbol"(ptr @ds) ]
  %imm.discr     = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 42) [ "deactivation-symbol"(ptr @ds) ]
  %addr.discr    = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 %addr) [ "deactivation-symbol"(ptr @ds) ]
  %blended.discr = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 %tmp) [ "deactivation-symbol"(ptr @ds) ]
  ret void
}

define void @test_ptrauth_resign(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_resign(
; CHECK-NEXT:    [[IMM_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 42, i64 0), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[ZERO_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 0), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[ADDR_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[BLENDED_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR]]), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[IMM_ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 123, i64 0), "ptrauth"(i64 2, i64 0, i64 0) ]
; CHECK-NEXT:    [[IMM_ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 123, i64 0), "ptrauth"(i64 2, i64 0, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[IMM_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 123, i64 0), "ptrauth"(i64 2, i64 5678, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[ZERO_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 0), "ptrauth"(i64 2, i64 4321, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[ADDR_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR]]), "ptrauth"(i64 2, i64 4321, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[BLENDED_ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 8765, i64 [[ADDR]]), "ptrauth"(i64 2, i64 0, i64 0) ]
; CHECK-NEXT:    [[BLENDED_ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 8765, i64 [[ADDR]]), "ptrauth"(i64 2, i64 0, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[BLENDED_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 111, i64 [[ADDR]]), "ptrauth"(i64 2, i64 222, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %imm.imm.discr     = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 42,    i32 2, i64 123)

  %tmp1 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %zero.imm.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 0,     i32 2, i64 123)
  %addr.imm.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %addr, i32 2, i64 123)
  %blended.imm.discr = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp1, i32 2, i64 123)

  %tmp2 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 5678)
  %imm.zero.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 123, i32 2, i64 0    )
  %imm.addr.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 123, i32 2, i64 %addr)
  %imm.blended.discr = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 123, i32 2, i64 %tmp2)

  %tmp3 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 4321)
  %zero.blended.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 0,     i32 2, i64 %tmp3)
  %addr.blended.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %addr, i32 2, i64 %tmp3)

  %tmp4 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 8765)
  %blended.zero.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp4, i32 2, i64 0    )
  %blended.addr.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp4, i32 2, i64 %addr)

  %tmp5 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 111)
  %tmp6 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 222)
  %blended.blended.discr = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp5,  i32 2, i64 %tmp6)

  ret void
}

define void @test_ptrauth_resign_load_relative(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_resign_load_relative(
; CHECK-NEXT:    [[IMM_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P:%.*]], i64 42) [ "ptrauth"(i64 1, i64 42, i64 0), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[ZERO_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 0, i64 0), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[ADDR_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[BLENDED_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR]]), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[IMM_ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 123, i64 0), "ptrauth"(i64 2, i64 0, i64 0) ]
; CHECK-NEXT:    [[IMM_ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 123, i64 0), "ptrauth"(i64 2, i64 0, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[IMM_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 123, i64 0), "ptrauth"(i64 2, i64 5678, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[ZERO_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 0, i64 0), "ptrauth"(i64 2, i64 4321, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[ADDR_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR]]), "ptrauth"(i64 2, i64 4321, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[BLENDED_ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 8765, i64 [[ADDR]]), "ptrauth"(i64 2, i64 0, i64 0) ]
; CHECK-NEXT:    [[BLENDED_ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 8765, i64 [[ADDR]]), "ptrauth"(i64 2, i64 0, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[BLENDED_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign.load.relative(i64 [[P]], i64 42) [ "ptrauth"(i64 1, i64 111, i64 [[ADDR]]), "ptrauth"(i64 2, i64 222, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %imm.imm.discr     = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 42,    i32 2, i64 123, i64 42)

  %tmp1 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %zero.imm.discr    = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 0,     i32 2, i64 123, i64 42)
  %addr.imm.discr    = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 %addr, i32 2, i64 123, i64 42)
  %blended.imm.discr = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 %tmp1, i32 2, i64 123, i64 42)

  %tmp2 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 5678)
  %imm.zero.discr    = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 123, i32 2, i64 0    , i64 42)
  %imm.addr.discr    = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 123, i32 2, i64 %addr, i64 42)
  %imm.blended.discr = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 123, i32 2, i64 %tmp2, i64 42)

  %tmp3 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 4321)
  %zero.blended.discr    = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 0,     i32 2, i64 %tmp3, i64 42)
  %addr.blended.discr    = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 %addr, i32 2, i64 %tmp3, i64 42)

  %tmp4 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 8765)
  %blended.zero.discr    = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 %tmp4, i32 2, i64 0    , i64 42)
  %blended.addr.discr    = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 %tmp4, i32 2, i64 %addr, i64 42)

  %tmp5 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 111)
  %tmp6 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 222)
  %blended.blended.discr = call i64 @llvm.ptrauth.resign.load.relative(i64 %p, i32 1, i64 %tmp5,  i32 2, i64 %tmp6, i64 42)

  ret void
}

define void @test_ptrauth_strip(i64 %p) {
; CHECK-LABEL: @test_ptrauth_strip(
; CHECK-NEXT:    [[RES:%.*]] = call i64 @llvm.ptrauth.strip(i64 [[P:%.*]]) [ "ptrauth"(i64 1) ]
; CHECK-NEXT:    ret void
;
  %res = call i64 @llvm.ptrauth.strip(i64 %p, i32 1)
  ret void
}

define void @test_ptrauth_reused_blend(i64 %p1, i64 %p2, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_reused_blend(
; CHECK-NEXT:    [[RES1:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P1:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR:%.*]]) ]
; CHECK-NEXT:    [[RES2:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P2:%.*]]) [ "ptrauth"(i64 2, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %res1 = call i64 @llvm.ptrauth.auth(i64 %p1, i32 1, i64 %tmp)
  %res2 = call i64 @llvm.ptrauth.auth(i64 %p2, i32 2, i64 %tmp)
  ret void
}

define void @test_ptrauth_reused_blend_same_inst(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_reused_blend_same_inst(
; CHECK-NEXT:    [[RES:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR:%.*]]), "ptrauth"(i64 2, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %res = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp, i32 2, i64 %tmp)
  ret void
}

define void @test_ptrauth_blend_in_other_bb(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_blend_in_other_bb(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    [[RES:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR:%.*]]), "ptrauth"(i64 2, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
entry:
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  br label %exit

exit:
  %res = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp, i32 2, i64 %tmp)
  ret void
}

define i64 @test_unused_blend(i64 %addr) {
; CHECK-LABEL: @test_unused_blend(
; CHECK-NEXT:    ret i64 [[ADDR:%.*]]
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  ret i64 %addr
}

define void @not_upgraded_store(ptr %p, i64 %addr) {
; CHECK-LABEL: @not_upgraded_store(
; CHECK-NEXT:    [[DISC:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[ADDR:%.*]], i64 42)
; CHECK-NEXT:    store i64 [[DISC]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  store i64 %disc, ptr %p
  ret void
}

define void @not_upgraded_arith(ptr %p, i64 %addr) {
; CHECK-LABEL: @not_upgraded_arith(
; CHECK-NEXT:    [[DISC:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[ADDR:%.*]], i64 42)
; CHECK-NEXT:    [[TMP:%.*]] = add i64 [[DISC]], 42
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  %tmp = add i64 %disc, 42
  ret void
}

define void @not_upgraded_indirect_one_arg(ptr %some_fn, i64 %addr) {
; CHECK-LABEL: @not_upgraded_indirect_one_arg(
; CHECK-NEXT:    [[DISC:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[ADDR:%.*]], i64 42)
; CHECK-NEXT:    call void [[SOME_FN:%.*]](i64 [[DISC]])
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  call void %some_fn(i64 %disc)
  ret void
}

declare void @some_fn(i64 %0)

define void @not_upgraded_direct_one_arg(i64 %addr) {
; CHECK-LABEL: @not_upgraded_direct_one_arg(
; CHECK-NEXT:    [[DISC:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[ADDR:%.*]], i64 42)
; CHECK-NEXT:    call void @some_fn(i64 [[DISC]])
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  call void @some_fn(i64 %disc)
  ret void
}

define void @not_upgraded_indirect_three_args(i64 %p, ptr %auth_like_fn, i64 %addr) {
; CHECK-LABEL: @not_upgraded_indirect_three_args(
; CHECK-NEXT:    [[DISC:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[ADDR:%.*]], i64 42)
; CHECK-NEXT:    call void [[AUTH_LIKE_FN:%.*]](i64 [[P:%.*]], i32 1, i64 [[DISC]])
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  call void %auth_like_fn(i64 %p, i32 1, i64 %disc)
  ret void
}

declare void @auth_like_fn(i64 %0, i32 %1, i64 %2)

define void @not_upgraded_direct_three_args(i64 %p, i64 %addr) {
; CHECK-LABEL: @not_upgraded_direct_three_args(
; CHECK-NEXT:    [[DISC:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[ADDR:%.*]], i64 42)
; CHECK-NEXT:    call void @auth_like_fn(i64 [[P:%.*]], i32 1, i64 [[DISC]])
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  call void @auth_like_fn(i64 %p, i32 1, i64 %disc)
  ret void
}

define void @not_upgraded_wrong_position_in_bundle(i64 %p, i64 %addr) {
; CHECK-LABEL: @not_upgraded_wrong_position_in_bundle(
; CHECK-NEXT:    [[DISC:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[ADDR:%.*]], i64 42)
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P:%.*]]) [ "ptrauth"(i64 [[DISC]], i64 1, i64 0) ]
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  call i64 @llvm.ptrauth.auth(i64 %p, i64 %disc, i64 1)
  ret void
}

define void @not_upgraded_both_positions_in_bundle(i64 %p, i64 %addr) {
; CHECK-LABEL: @not_upgraded_both_positions_in_bundle(
; CHECK-NEXT:    [[DISC:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[ADDR:%.*]], i64 42)
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P:%.*]]) [ "ptrauth"(i64 [[DISC]], i64 42, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  call i64 @llvm.ptrauth.auth(i64 %p, i64 %disc, i64 %disc)
  ret void
}
