; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S < %s    | FileCheck %s
; RUN: opt -S < %s.bc | FileCheck %s

define void @test_call_imm_disc(ptr %fn) {
; CHECK-LABEL: @test_call_imm_disc(
; CHECK-NEXT:    call void [[FN:%.*]]() [ "ptrauth"(i64 1, i64 0, i64 0) ]
; CHECK-NEXT:    call void [[FN]]() [ "ptrauth"(i64 1, i64 42, i64 0) ]
; CHECK-NEXT:    ret void
;
  call void %fn() [ "ptrauth"(i32 1, i64 0) ]
  call void %fn() [ "ptrauth"(i32 1, i64 42) ]
  ret void
}

define void @test_call_addr_disc(ptr %fn, i64 %addr) {
; CHECK-LABEL: @test_call_addr_disc(
; CHECK-NEXT:    call void [[FN:%.*]]() [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]) ]
; CHECK-NEXT:    ret void
;
  call void %fn() [ "ptrauth"(i32 1, i64 %addr) ]
  ret void
}

define void @test_call_blended_disc(ptr %fn, i64 %addr) {
; CHECK-LABEL: @test_call_blended_disc(
; CHECK-NEXT:    call void [[FN:%.*]]() [ "ptrauth"(i64 1, i64 42, i64 [[ADDR:%.*]]) ]
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  call void %fn() [ "ptrauth"(i32 1, i64 %disc) ]
  ret void
}

; More realistic variant of partially-upgraded call instruction inspired by
; @both_positions_in_bundle from ptrauth-intrinsics-upgrade.ll: in this example,
; the result of the same blend intrinsic call is used twice by the same llvm::User:
; once as the discriminator to be upgraded and once more as an opaque function
; argument. Make sure the upgrader does not crash trying to upgrade this.
define void @auth_call_blended_disc_and_arg(ptr %fn, i64 %addr) {
; CHECK-LABEL: @auth_call_blended_disc_and_arg(
; CHECK-NEXT:    [[DISC:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[ADDR:%.*]], i64 42)
; CHECK-NEXT:    call void [[FN:%.*]](i64 [[DISC]]) [ "ptrauth"(i64 1, i64 42, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 42)
  call void %fn(i64 %disc) [ "ptrauth"(i32 1, i64 %disc) ]
  ret void
}
