; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define ptr @test_ptrauth_nop(ptr %p) {
; CHECK-LABEL: @test_ptrauth_nop(
; CHECK-NEXT:    ret ptr [[P:%.*]]
;
  %tmp0 = ptrtoint ptr %p to i64
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_long_bundle_ops(ptr %p) {
; CHECK-LABEL: @test_ptrauth_nop_long_bundle_ops(
; CHECK-NEXT:    ret ptr [[P:%.*]]
;
  %tmp0 = ptrtoint ptr %p to i64
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 42, i64 %tmp0) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 42, i64 %tmp0) ]
  ret ptr %authed
}

declare void @foo()
declare void @bar()

define ptr @test_ptrauth_nop_constant() {
; CHECK-LABEL: @test_ptrauth_nop_constant(
; CHECK-NEXT:    ret ptr @foo
;
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 0])) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_constant_addrdisc() {
; CHECK-LABEL: @test_ptrauth_nop_constant_addrdisc(
; CHECK-NEXT:    ret ptr @foo
;
  %addr = ptrtoint ptr @foo to i64
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 ptrtoint (ptr @foo to i64)])) [ "ptrauth"(i64 1, i64 1234, i64 %addr) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_constant_long_bundle() {
; CHECK-LABEL: @test_ptrauth_nop_constant_long_bundle(
; CHECK-NEXT:    ret ptr @foo
;
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64)])) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64)) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_mismatch(ptr %p) {
; CHECK-LABEL: @test_ptrauth_nop_mismatch(
; CHECK-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.sign.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[SIGNED]]) [ "ptrauth"(i64 1, i64 10, i64 0) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 1, i64 10, i64 0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_mismatch_keys(ptr %p) {
; CHECK-LABEL: @test_ptrauth_nop_mismatch_keys(
; CHECK-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.sign.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 0, i64 1234, i64 0) ]
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[SIGNED]]) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 0, i64 1234, i64 0) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_long_bundle_ops_mismatch(ptr %p) {
; CHECK-LABEL: @test_ptrauth_nop_long_bundle_ops_mismatch(
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[P:%.*]] to i64
; CHECK-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.sign.p0(ptr [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 42, i64 [[TMP0]]) ]
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[SIGNED]]) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 42, i64 123) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %tmp0 = ptrtoint ptr %p to i64
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 42, i64 %tmp0) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 42, i64 123) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_constant_long_bundle_mismatch_ints() {
; CHECK-LABEL: @test_ptrauth_nop_constant_long_bundle_mismatch_ints(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr nonnull ptrauth (ptr @foo, [i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64), i64 42])) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64), i64 1) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64), i64 42])) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64), i64 1) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_constant_long_bundle_mismatch_ptrs() {
; CHECK-LABEL: @test_ptrauth_nop_constant_long_bundle_mismatch_ptrs(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr nonnull ptrauth (ptr @foo, [i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @foo to i64)])) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64)) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @foo to i64)])) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64)) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_constant_long_bundle_mismatch_int_vs_ptr() {
; CHECK-LABEL: @test_ptrauth_nop_constant_long_bundle_mismatch_int_vs_ptr(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr nonnull ptrauth (ptr @foo, [i64 1, i64 1234, i64 0, i64 42])) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64)) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 0, i64 42])) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 ptrtoint (ptr @bar to i64)) ]
  ret ptr %authed
}

define ptr @test_ptrauth_sign_resign(ptr %p) {
; CHECK-LABEL: @test_ptrauth_sign_resign(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.sign.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 0, i64 42, i64 0) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %tmp0 = ptrtoint ptr %p to i64
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 42, i64 %tmp0) ]
  %authed = call ptr @llvm.ptrauth.resign.p0(ptr %signed) [ "ptrauth"(i64 1, i64 1234, i64 0, i64 42, i64 %tmp0), "ptrauth"(i64 0, i64 42, i64 0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_resign_resign(ptr %p) {
; CHECK-LABEL: @test_ptrauth_resign_resign(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.resign.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 1, i64 3141, i64 0) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %tmp0 = ptrtoint ptr %p to i64
  %signed = call ptr @llvm.ptrauth.resign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 0, i64 42, i64 0, i64 42, i64 %tmp0) ]
  %authed = call ptr @llvm.ptrauth.resign.p0(ptr %signed) [ "ptrauth"(i64 0, i64 42, i64 0, i64 42, i64 %tmp0), "ptrauth"(i64 1, i64 3141, i64 0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_resign_auth(ptr %p) {
; CHECK-LABEL: @test_ptrauth_resign_auth(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %tmp0 = ptrtoint ptr %p to i64
  %signed = call ptr @llvm.ptrauth.resign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 0, i64 42, i64 0, i64 42, i64 %tmp0) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 0, i64 42, i64 0, i64 42, i64 %tmp0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_resign_auth_mismatch(ptr %p) {
; CHECK-LABEL: @test_ptrauth_resign_auth_mismatch(
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[P:%.*]] to i64
; CHECK-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.resign.p0(ptr [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 0, i64 10, i64 0, i64 42, i64 [[TMP0]]) ]
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[SIGNED]]) [ "ptrauth"(i64 0, i64 42, i64 0, i64 123, i64 [[TMP0]]) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %tmp0 = ptrtoint ptr %p to i64
  %signed = call ptr @llvm.ptrauth.resign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 0, i64 10, i64 0, i64 42, i64 %tmp0) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 0, i64 42, i64 0, i64 123, i64 %tmp0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_constant_mismatch() {
; CHECK-LABEL: @test_ptrauth_nop_constant_mismatch(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr nonnull ptrauth (ptr @foo, [i64 1, i64 1234, i64 0])) [ "ptrauth"(i64 1, i64 12, i64 0) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 0])) [ "ptrauth"(i64 1, i64 12, i64 0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_constant_mismatch_key() {
; CHECK-LABEL: @test_ptrauth_nop_constant_mismatch_key(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr nonnull ptrauth (ptr @foo, [i64 1, i64 1234, i64 0])) [ "ptrauth"(i64 0, i64 1234, i64 0) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 0])) [ "ptrauth"(i64 0, i64 1234, i64 0) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_constant_addrdisc_mismatch() {
; CHECK-LABEL: @test_ptrauth_nop_constant_addrdisc_mismatch(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr nonnull ptrauth (ptr @foo, [i64 1, i64 1234, i64 ptrtoint (ptr @foo to i64)])) [ "ptrauth"(i64 1, i64 12, i64 ptrtoint (ptr @foo to i64)) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %addr = ptrtoint ptr @foo to i64
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 ptrtoint (ptr @foo to i64)])) [ "ptrauth"(i64 1, i64 12, i64 %addr) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_constant_addrdisc_mismatch2() {
; CHECK-LABEL: @test_ptrauth_nop_constant_addrdisc_mismatch2(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr nonnull ptrauth (ptr @foo, [i64 1, i64 1234, i64 ptrtoint (ptr @foo to i64)])) [ "ptrauth"(i64 1, i64 1234, i64 ptrtoint (ptr @bar to i64)) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %addr = ptrtoint ptr @bar to i64
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 ptrtoint (ptr @foo to i64)])) [ "ptrauth"(i64 1, i64 1234, i64 %addr) ]
  ret ptr %authed
}

define ptr @test_ptrauth_resign_ptrauth_constant(ptr %p) {
; CHECK-LABEL: @test_ptrauth_resign_ptrauth_constant(
; CHECK-NEXT:    ret ptr ptrauth (ptr @foo, [i64 0, i64 42, i64 0])
;

  %authed = call ptr @llvm.ptrauth.resign.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 0])) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 0, i64 42, i64 0) ]
  ret ptr %authed
}

@ds = external global i8
@ds2 = external global i8

define ptr @test_ptrauth_nop_ds1(ptr %p) {
; CHECK-LABEL: @test_ptrauth_nop_ds1(
; CHECK-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.sign.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[SIGNED]]) [ "ptrauth"(i64 1, i64 1234) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234), "deactivation-symbol"(ptr @ds) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 1, i64 1234) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_ds2(ptr %p) {
; CHECK-LABEL: @test_ptrauth_nop_ds2(
; CHECK-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.sign.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234) ]
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[SIGNED]]) [ "ptrauth"(i64 1, i64 1234), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 1, i64 1234), "deactivation-symbol"(ptr @ds) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_ds3(ptr %p) {
; CHECK-LABEL: @test_ptrauth_nop_ds3(
; CHECK-NEXT:    [[SIGNED:%.*]] = call ptr @llvm.ptrauth.sign.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 0), "deactivation-symbol"(ptr @ds) ]
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[SIGNED]]) [ "ptrauth"(i64 1, i64 1234, i64 0), "deactivation-symbol"(ptr @ds2) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0), "deactivation-symbol"(ptr @ds) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 1, i64 1234, i64 0), "deactivation-symbol"(ptr @ds2) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_ds4(ptr %p) {
; CHECK-LABEL: @test_ptrauth_nop_ds4(
; CHECK-NEXT:    ret ptr [[P:%.*]]
;
  %signed = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0), "deactivation-symbol"(ptr @ds) ]
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %signed) [ "ptrauth"(i64 1, i64 1234, i64 0), "deactivation-symbol"(ptr @ds) ]
  ret ptr %authed
}

define ptr @test_ptrauth_nop_ds_constant() {
; CHECK-LABEL: @test_ptrauth_nop_ds_constant(
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr nonnull ptrauth (ptr @foo, [i64 1, i64 1234, i64 0], ptr @ds)) [ "ptrauth"(i64 1, i64 1234) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr ptrauth(ptr @foo, [i64 1, i64 1234, i64 0], ptr @ds)) [ "ptrauth"(i64 1, i64 1234) ]
  ret ptr %authed
}

define ptr @test_ptrauth_auth_call_no_args() {
; CHECK-LABEL: @test_ptrauth_auth_call_no_args(
; CHECK-NEXT:    [[CALL:%.*]] = call ptr @foo()
; CHECK-NEXT:    [[AUTHED:%.*]] = call ptr @llvm.ptrauth.auth.p0(ptr [[CALL]]) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
; CHECK-NEXT:    ret ptr [[AUTHED]]
;
  %call = call ptr @foo()
  %authed = call ptr @llvm.ptrauth.auth.p0(ptr %call) [ "ptrauth"(i64 1, i64 1234, i64 0) ]
  ret ptr %authed
}

declare i64 @llvm.ptrauth.auth(i64)
declare i64 @llvm.ptrauth.sign(i64)
declare i64 @llvm.ptrauth.resign(i64)
declare i64 @llvm.ptrauth.blend(i64, i64)
