; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i32 @test_ptrauth_call_sign(ptr %p) {
; CHECK-LABEL: @test_ptrauth_call_sign(
; CHECK-NEXT:    [[V3:%.*]] = call i32 [[P:%.*]]()
; CHECK-NEXT:    ret i32 [[V3]]
;
  %v1 = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 2, i64 5678, i64 0) ]
  %v3 = call i32 %v1() [ "ptrauth"(i64 2, i64 5678, i64 0) ]
  ret i32 %v3
}

define i32 @test_ptrauth_call_sign_otherbundle(ptr %p) {
; CHECK-LABEL: @test_ptrauth_call_sign_otherbundle(
; CHECK-NEXT:    [[V3:%.*]] = call i32 [[P:%.*]]() [ "somebundle"(ptr null), "otherbundle"(i64 0) ]
; CHECK-NEXT:    ret i32 [[V3]]
;
  %v1 = call ptr @llvm.ptrauth.sign.p0(ptr %p) [ "ptrauth"(i64 2, i64 5678, i64 0) ]
  %v3 = call i32 %v1() [ "somebundle"(ptr null), "ptrauth"(i64 2, i64 5678, i64 0), "otherbundle"(i64 0) ]
  ret i32 %v3
}

define i32 @test_ptrauth_call_resign(ptr %p) {
; CHECK-LABEL: @test_ptrauth_call_resign(
; CHECK-NEXT:    [[V3:%.*]] = call i32 [[P:%.*]]() [ "ptrauth"(i64 1, i64 1234, i64 0) ]
; CHECK-NEXT:    ret i32 [[V3]]
;
  %v1 = call ptr @llvm.ptrauth.resign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 1, i64 5678, i64 0) ]
  %v3 = call i32 %v1() [ "ptrauth"(i64 1, i64 5678, i64 0) ]
  ret i32 %v3
}

define i32 @test_ptrauth_call_resign_blend(ptr %pp) {
; CHECK-LABEL: @test_ptrauth_call_resign_blend(
; CHECK-NEXT:    [[V01:%.*]] = load ptr, ptr [[PP:%.*]], align 8
; CHECK-NEXT:    [[V6:%.*]] = call i32 [[V01]]() [ "ptrauth"(i64 1, i64 1234, i64 0) ]
; CHECK-NEXT:    ret i32 [[V6]]
;
  %v0 = load ptr, ptr %pp, align 8
  %v1 = ptrtoint ptr %pp to i64
  %v4 = call ptr @llvm.ptrauth.resign.p0(ptr %v0) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 1, i64 5678, i64 %v1) ]
  %v6 = call i32 %v4() [ "ptrauth"(i64 1, i64 5678, i64 %v1) ]
  ret i32 %v6
}

define i32 @test_ptrauth_call_resign_blend_2(ptr %pp) {
; CHECK-LABEL: @test_ptrauth_call_resign_blend_2(
; CHECK-NEXT:    [[V01:%.*]] = load ptr, ptr [[PP:%.*]], align 8
; CHECK-NEXT:    [[V1:%.*]] = ptrtoint ptr [[PP]] to i64
; CHECK-NEXT:    [[V6:%.*]] = call i32 [[V01]]() [ "ptrauth"(i64 0, i64 5678, i64 [[V1]]) ]
; CHECK-NEXT:    ret i32 [[V6]]
;
  %v0 = load ptr, ptr %pp, align 8
  %v1 = ptrtoint ptr %pp to i64
  %v4 = call ptr @llvm.ptrauth.resign.p0(ptr %v0) [ "ptrauth"(i64 0, i64 5678, i64 %v1), "ptrauth"(i64 0, i64 1234, i64 0) ]
  %v6 = call i32 %v4() [ "ptrauth"(i64 0, i64 1234, i64 0) ]
  ret i32 %v6
}

define i32 @test_ptrauth_call_resign_long_bundle_ops(ptr %pp) {
; CHECK-LABEL: @test_ptrauth_call_resign_long_bundle_ops(
; CHECK-NEXT:    [[V01:%.*]] = load ptr, ptr [[PP:%.*]], align 8
; CHECK-NEXT:    [[V6:%.*]] = call i32 [[V01]]() [ "ptrauth"(i64 1, i64 1234) ]
; CHECK-NEXT:    ret i32 [[V6]]
;
  %v0 = load ptr, ptr %pp, align 8
  %v1 = ptrtoint ptr %pp to i64
  %v2 = ptrtoint ptr %v0 to i64
  %v4 = call ptr @llvm.ptrauth.resign.p0(ptr %v0) [ "ptrauth"(i64 1, i64 1234), "ptrauth"(i64 1, i64 %v1, i64 5678, i64 %v2, i64 123) ]
  %v6 = call i32 %v4() [ "ptrauth"(i64 1, i64 %v1, i64 5678, i64 %v2, i64 123) ]
  ret i32 %v6
}

define i32 @test_ptrauth_call_resign_mismatch_key(ptr %p) {
; CHECK-LABEL: @test_ptrauth_call_resign_mismatch_key(
; CHECK-NEXT:    [[V2:%.*]] = call ptr @llvm.ptrauth.resign.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 0, i64 5678, i64 0) ]
; CHECK-NEXT:    [[V3:%.*]] = call i32 [[V2]]() [ "ptrauth"(i64 1, i64 5678, i64 0) ]
; CHECK-NEXT:    ret i32 [[V3]]
;
  %v1 = call ptr @llvm.ptrauth.resign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 0, i64 5678, i64 0) ]
  %v3 = call i32 %v1() [ "ptrauth"(i64 1, i64 5678, i64 0) ]
  ret i32 %v3
}

define i32 @test_ptrauth_call_resign_mismatch_disc(ptr %p) {
; CHECK-LABEL: @test_ptrauth_call_resign_mismatch_disc(
; CHECK-NEXT:    [[V2:%.*]] = call ptr @llvm.ptrauth.resign.p0(ptr [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 0, i64 9900, i64 0) ]
; CHECK-NEXT:    [[V3:%.*]] = call i32 [[V2]]() [ "ptrauth"(i64 1, i64 5678, i64 0) ]
; CHECK-NEXT:    ret i32 [[V3]]
;
  %v1 = call ptr @llvm.ptrauth.resign.p0(ptr %p) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 0, i64 9900, i64 0) ]
  %v3 = call i32 %v1() [ "ptrauth"(i64 1, i64 5678, i64 0) ]
  ret i32 %v3
}

define i32 @test_ptrauth_call_resign_mismatch_blend(ptr %pp) {
; CHECK-LABEL: @test_ptrauth_call_resign_mismatch_blend(
; CHECK-NEXT:    [[V0:%.*]] = load ptr, ptr [[PP:%.*]], align 8
; CHECK-NEXT:    [[V1:%.*]] = ptrtoint ptr [[PP]] to i64
; CHECK-NEXT:    [[V5:%.*]] = call ptr @llvm.ptrauth.resign.p0(ptr [[V0]]) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 1, i64 5678, i64 [[V1]]) ]
; CHECK-NEXT:    [[V3:%.*]] = call i32 [[V5]]() [ "ptrauth"(i64 1, i64 0, i64 [[V1]]) ]
; CHECK-NEXT:    ret i32 [[V3]]
;
  %v0 = load ptr, ptr %pp, align 8
  %v1 = ptrtoint ptr %pp to i64
  %v4 = call ptr @llvm.ptrauth.resign.p0(ptr %v0) [ "ptrauth"(i64 1, i64 1234, i64 0), "ptrauth"(i64 1, i64 5678, i64 %v1) ]
  %v6 = call i32 %v4() [ "ptrauth"(i64 1, i64 0, i64 %v1) ]
  ret i32 %v6
}

define i32 @test_ptrauth_call_resign_long_bundle_ops_mismatch(ptr %pp) {
; CHECK-LABEL: @test_ptrauth_call_resign_long_bundle_ops_mismatch(
; CHECK-NEXT:    [[V0:%.*]] = load ptr, ptr [[PP:%.*]], align 8
; CHECK-NEXT:    [[V1:%.*]] = ptrtoint ptr [[PP]] to i64
; CHECK-NEXT:    [[V2:%.*]] = ptrtoint ptr [[V0]] to i64
; CHECK-NEXT:    [[V5:%.*]] = call ptr @llvm.ptrauth.resign.p0(ptr [[V0]]) [ "ptrauth"(i64 1, i64 1234), "ptrauth"(i64 1, i64 [[V1]], i64 5678, i64 [[V1]], i64 123) ]
; CHECK-NEXT:    [[V3:%.*]] = call i32 [[V5]]() [ "ptrauth"(i64 1, i64 [[V1]], i64 [[V2]], i64 123) ]
; CHECK-NEXT:    ret i32 [[V3]]
;
  %v0 = load ptr, ptr %pp, align 8
  %v1 = ptrtoint ptr %pp to i64
  %v2 = ptrtoint ptr %v0 to i64
  %v4 = call ptr @llvm.ptrauth.resign.p0(ptr %v0) [ "ptrauth"(i64 1, i64 1234), "ptrauth"(i64 1, i64 %v1, i64 5678, i64 %v1, i64 123) ]
  %v6 = call i32 %v4() [ "ptrauth"(i64 1, i64 %v1, i64 %v2, i64 123) ]
  ret i32 %v6
}

define i32 @test_ptrauth_call_resign_changing_call_key(ptr %p) {
; CHECK-LABEL: @test_ptrauth_call_resign_changing_call_key(
; CHECK-NEXT:    [[V3:%.*]] = call i32 [[P:%.*]]() [ "ptrauth"(i64 2, i64 1234, i64 0) ]
; CHECK-NEXT:    ret i32 [[V3]]
;
  %v1 = call ptr @llvm.ptrauth.resign.p0(ptr %p) [ "ptrauth"(i64 2, i64 1234, i64 0), "ptrauth"(i64 1, i64 5678, i64 0) ]
  %v3 = call i32 %v1() [ "ptrauth"(i64 1, i64 5678, i64 0) ]
  ret i32 %v3
}
