; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --version 5
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=aarch64-linux-pauthtest -S -passes='require<profile-summary>,function(codegenprepare)' < %s | FileCheck --check-prefix=IR %s
; RUN: opt -mtriple=arm64e-apple-darwin     -S -passes='require<profile-summary>,function(codegenprepare)' < %s | FileCheck --check-prefix=IR %s
; RUN: llc -mtriple=aarch64-linux-pauthtest -mattr=+pauth -start-before=codegenprepare < %s | FileCheck --check-prefix=ASM-ELF %s
; RUN: llc -mtriple=arm64e-apple-darwin                   -start-before=codegenprepare < %s | FileCheck --check-prefix=ASM-DARWIN %s

; Auth / sign / resign pseudo instructions have separate components for address
; and immediate parts of the discriminator. This way, even if an attacker is
; able to substitute address modifier, it is still possible to blend the
; immediate modifier by MOVK right before actual usage of the discriminator.
;
; At the LLVM IR level, it is possible for discriminator to be computed by
; @llvm.ptrauth.blend and used by @llvm.ptrauth.(auth|sign|resign) in different
; basic blocks. Moreover, it is common for VTT initialization in C++ to induce
; many @llvm.ptrauth.blend operations with different address and the same
; immediate modifiers passed to their user via phi node.
;
; In codegenprepare, the below pattern
;
; bb.blend.1:
;   %disc.1 = call i64 @llvm.ptrauth.blend(i64 %addr.1, i64 COMMON_IMM)
; bb.blend.2:
;   %disc.2 = call i64 @llvm.ptrauth.blend(i64 %addr.2, i64 COMMON_IMM)
; ...
; bb.phi:
;   %disc = phi i64 [ %disc.1, %bb.blend.1 ], [ %disc.2, %bb.blend.2 ], ...
; bb.user:
;   %result = call @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %disc)
;
; is detected and rewritten like this
;
; bb.blend.1:
;   ...
; bb.blend.2:
;   ...
; bb.phi:
;   %addr = phi i64 [ %addr.1, %bb.blend.1 ], [ %addr.2, %bb.blend.2 ], ...
;   %disc = call i64 @llvm.ptrauth.blend(i64 %addr, i64 COMMON_IMM)
; bb.user:
;   %result = call @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %disc)

define i64 @choose_disc(i1 %cond, i64 %addr.1, i64 %addr.2, i64 %ptr) {
; IR-LABEL: define i64 @choose_disc(i1 %cond, i64 %addr.1, i64 %addr.2, i64 %ptr) {
; IR-NEXT:  entry:
; IR-NEXT:    br i1 %cond, label %bb.blend.1, label %bb.blend.2
; IR:       bb.blend.1:
; IR-NEXT:    %disc.1 = call i64 @llvm.ptrauth.blend(i64 %addr.1, i64 1234)
; IR-NEXT:    br label %bb.user
; IR:       bb.blend.2:
; IR-NEXT:    %disc.2 = call i64 @llvm.ptrauth.blend(i64 %addr.2, i64 1234)
; IR-NEXT:    br label %bb.user
; IR:       bb.user:
; IR-NEXT:    %0 = phi i64 [ %addr.1, %bb.blend.1 ], [ %addr.2, %bb.blend.2 ]
; IR-NEXT:    %disc = phi i64 [ %disc.1, %bb.blend.1 ], [ %disc.2, %bb.blend.2 ]
; IR-NEXT:    %1 = call i64 @llvm.ptrauth.blend(i64 %0, i64 1234)
; IR-NEXT:    %result = call i64 @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %1)
; IR-NEXT:    ret i64 %result
;
; ASM-ELF-LABEL: choose_disc:
; ASM-ELF:       // %bb.0: // %entry
; ASM-ELF-NEXT:    tst w0, #0x1
; ASM-ELF-NEXT:    csel x8, x2, x1, eq
; ASM-ELF-NEXT:    mov x17, x8
; ASM-ELF-NEXT:    movk x17, #1234, lsl #48
; ASM-ELF-NEXT:    pacia x3, x17
; ASM-ELF-NEXT:    mov x0, x3
; ASM-ELF-NEXT:    ret
;
; ASM-DARWIN-LABEL: choose_disc:
; ASM-DARWIN:       ; %bb.0: ; %entry
; ASM-DARWIN-NEXT:    tst w0, #0x1
; ASM-DARWIN-NEXT:    csel x8, x2, x1, eq
; ASM-DARWIN-NEXT:    mov x17, x8
; ASM-DARWIN-NEXT:    movk x17, #1234, lsl #48
; ASM-DARWIN-NEXT:    pacia x3, x17
; ASM-DARWIN-NEXT:    mov x0, x3
; ASM-DARWIN-NEXT:    ret
entry:
  br i1 %cond, label %bb.blend.1, label %bb.blend.2
bb.blend.1:
  %disc.1 = call i64 @llvm.ptrauth.blend(i64 %addr.1, i64 1234)
  br label %bb.user
bb.blend.2:
  %disc.2 = call i64 @llvm.ptrauth.blend(i64 %addr.2, i64 1234)
  br label %bb.user
bb.user:
  %disc = phi i64 [ %disc.1, %bb.blend.1 ], [ %disc.2, %bb.blend.2 ]
  %result = call i64 @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %disc)
  ret i64 %result
}

define i64 @choose_disc_different_imm(i1 %cond, i64 %addr.1, i64 %addr.2, i64 %ptr) {
; IR-LABEL: define i64 @choose_disc_different_imm(i1 %cond, i64 %addr.1, i64 %addr.2, i64 %ptr) {
; IR-NEXT:  entry:
; IR-NEXT:    br i1 %cond, label %bb.blend.1, label %bb.blend.2
; IR:       bb.blend.1:
; IR-NEXT:    %disc.1 = call i64 @llvm.ptrauth.blend(i64 %addr.1, i64 1234)
; IR-NEXT:    br label %bb.user
; IR:       bb.blend.2:
; IR-NEXT:    %disc.2 = call i64 @llvm.ptrauth.blend(i64 %addr.2, i64 42)
; IR-NEXT:    br label %bb.user
; IR:       bb.user:
; IR-NEXT:    %disc = phi i64 [ %disc.1, %bb.blend.1 ], [ %disc.2, %bb.blend.2 ]
; IR-NEXT:    %result = call i64 @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %disc)
; IR-NEXT:    ret i64 %result
;
; ASM-ELF-LABEL: choose_disc_different_imm:
; ASM-ELF:       // %bb.0: // %entry
; ASM-ELF-NEXT:    movk x2, #42, lsl #48
; ASM-ELF-NEXT:    movk x1, #1234, lsl #48
; ASM-ELF-NEXT:    tst w0, #0x1
; ASM-ELF-NEXT:    csel x8, x2, x1, eq
; ASM-ELF-NEXT:    pacia x3, x8
; ASM-ELF-NEXT:    mov x0, x3
; ASM-ELF-NEXT:    ret
;
; ASM-DARWIN-LABEL: choose_disc_different_imm:
; ASM-DARWIN:       ; %bb.0: ; %entry
; ASM-DARWIN-NEXT:    movk x2, #42, lsl #48
; ASM-DARWIN-NEXT:    movk x1, #1234, lsl #48
; ASM-DARWIN-NEXT:    tst w0, #0x1
; ASM-DARWIN-NEXT:    csel x8, x2, x1, eq
; ASM-DARWIN-NEXT:    pacia x3, x8
; ASM-DARWIN-NEXT:    mov x0, x3
; ASM-DARWIN-NEXT:    ret
entry:
  br i1 %cond, label %bb.blend.1, label %bb.blend.2
bb.blend.1:
  %disc.1 = call i64 @llvm.ptrauth.blend(i64 %addr.1, i64 1234)
  br label %bb.user
bb.blend.2:
  %disc.2 = call i64 @llvm.ptrauth.blend(i64 %addr.2, i64 42)
  br label %bb.user
bb.user:
  %disc = phi i64 [ %disc.1, %bb.blend.1 ], [ %disc.2, %bb.blend.2 ]
  %result = call i64 @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %disc)
  ret i64 %result
}

define i64 @choose_disc_multi_edge(i32 %arg, i64 %addr.1, i64 %addr.2, i64 %ptr) {
; IR-LABEL: define i64 @choose_disc_multi_edge(i32 %arg, i64 %addr.1, i64 %addr.2, i64 %ptr) {
; IR-NEXT:  entry:
; IR-NEXT:    %cond = icmp eq i32 %arg, 0
; IR-NEXT:    br i1 %cond, label %bb.blend.1, label %bb.blend.2
; IR:       bb.blend.1:
; IR-NEXT:    %disc.1 = call i64 @llvm.ptrauth.blend(i64 %addr.1, i64 1234)
; IR-NEXT:    %cond1 = icmp eq i32 %arg, 0
; IR-NEXT:    br i1 %cond1, label %bb.blend.2, label %bb.user
; IR:       bb.blend.2:
; IR-NEXT:    %disc.2 = call i64 @llvm.ptrauth.blend(i64 %addr.2, i64 1234)
; IR-NEXT:    br label %bb.user
; IR:       bb.user:
; IR-NEXT:    %0 = phi i64 [ %addr.1, %bb.blend.1 ], [ %addr.2, %bb.blend.2 ]
; IR-NEXT:    %disc = phi i64 [ %disc.1, %bb.blend.1 ], [ %disc.2, %bb.blend.2 ]
; IR-NEXT:    %1 = call i64 @llvm.ptrauth.blend(i64 %0, i64 1234)
; IR-NEXT:    %result = call i64 @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %1)
; IR-NEXT:    ret i64 %result
;
; ASM-ELF-LABEL: choose_disc_multi_edge:
; ASM-ELF:       // %bb.0: // %entry
; ASM-ELF-NEXT:    cbz w0, .LBB2_2
; ASM-ELF-NEXT:  .LBB2_1: // %bb.blend.2
; ASM-ELF-NEXT:    mov x1, x2
; ASM-ELF-NEXT:    b .LBB2_3
; ASM-ELF-NEXT:  .LBB2_2: // %bb.blend.1
; ASM-ELF-NEXT:    cbz w0, .LBB2_1
; ASM-ELF-NEXT:  .LBB2_3: // %bb.user
; ASM-ELF-NEXT:    mov x17, x1
; ASM-ELF-NEXT:    movk x17, #1234, lsl #48
; ASM-ELF-NEXT:    pacia x3, x17
; ASM-ELF-NEXT:    mov x0, x3
; ASM-ELF-NEXT:    ret
;
; ASM-DARWIN-LABEL: choose_disc_multi_edge:
; ASM-DARWIN:       ; %bb.0: ; %entry
; ASM-DARWIN-NEXT:    cbz w0, LBB2_2
; ASM-DARWIN-NEXT:  LBB2_1: ; %bb.blend.2
; ASM-DARWIN-NEXT:    mov x1, x2
; ASM-DARWIN-NEXT:    b LBB2_3
; ASM-DARWIN-NEXT:  LBB2_2: ; %bb.blend.1
; ASM-DARWIN-NEXT:    cbz w0, LBB2_1
; ASM-DARWIN-NEXT:  LBB2_3: ; %bb.user
; ASM-DARWIN-NEXT:    mov x17, x1
; ASM-DARWIN-NEXT:    movk x17, #1234, lsl #48
; ASM-DARWIN-NEXT:    pacia x3, x17
; ASM-DARWIN-NEXT:    mov x0, x3
; ASM-DARWIN-NEXT:    ret
entry:
  %cond = icmp eq i32 %arg, 0
  br i1 %cond, label %bb.blend.1, label %bb.blend.2
bb.blend.1:
  %disc.1 = call i64 @llvm.ptrauth.blend(i64 %addr.1, i64 1234)
  switch i32 %arg, label %bb.user [i32 0, label %bb.blend.2 i32 2, label %bb.user]
bb.blend.2:
  %disc.2 = call i64 @llvm.ptrauth.blend(i64 %addr.2, i64 1234)
  br label %bb.user
bb.user:
  %disc = phi i64 [ %disc.1, %bb.blend.1 ], [ %disc.1, %bb.blend.1 ], [ %disc.2, %bb.blend.2 ]
  %result = call i64 @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %disc)
  ret i64 %result
}

define i64 @choose_disc_phi_placement(i1 %cond, i64 %addr.1, i64 %addr.2, i64 %ptr) {
; IR-LABEL: define i64 @choose_disc_phi_placement(i1 %cond, i64 %addr.1, i64 %addr.2, i64 %ptr) {
; IR-NEXT:  entry:
; IR-NEXT:    br i1 %cond, label %bb.blend.1, label %bb.blend.2
; IR:       bb.blend.1:
; IR-NEXT:    %disc.1 = call i64 @llvm.ptrauth.blend(i64 %addr.1, i64 1234)
; IR-NEXT:    br label %bb.phi
; IR:       bb.blend.2:
; IR-NEXT:    %disc.2 = call i64 @llvm.ptrauth.blend(i64 %addr.2, i64 1234)
; IR-NEXT:    br label %bb.phi
; IR:       bb.phi:
; IR-NEXT:    %0 = phi i64 [ %addr.1, %bb.blend.1 ], [ %addr.2, %bb.blend.2 ]
; IR-NEXT:    %disc = phi i64 [ %disc.1, %bb.blend.1 ], [ %disc.2, %bb.blend.2 ]
; IR-NEXT:    br i1 %cond, label %bb.user, label %bb.ret0
; IR:       bb.user:
; IR-NEXT:    %1 = call i64 @llvm.ptrauth.blend(i64 %0, i64 1234)
; IR-NEXT:    %result = call i64 @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %1)
; IR-NEXT:    ret i64 %result
; IR:       bb.ret0:
; IR-NEXT:    ret i64 0
;
; ASM-ELF-LABEL: choose_disc_phi_placement:
; ASM-ELF:       // %bb.0: // %entry
; ASM-ELF-NEXT:    tbnz w0, #0, .LBB3_2
; ASM-ELF-NEXT:  // %bb.1: // %bb.blend.2
; ASM-ELF-NEXT:    mov x1, x2
; ASM-ELF-NEXT:  .LBB3_2: // %bb.phi
; ASM-ELF-NEXT:    tbz w0, #0, .LBB3_4
; ASM-ELF-NEXT:  // %bb.3: // %bb.user
; ASM-ELF-NEXT:    mov x17, x1
; ASM-ELF-NEXT:    movk x17, #1234, lsl #48
; ASM-ELF-NEXT:    pacia x3, x17
; ASM-ELF-NEXT:    mov x0, x3
; ASM-ELF-NEXT:    ret
; ASM-ELF-NEXT:  .LBB3_4: // %bb.ret0
; ASM-ELF-NEXT:    mov x0, xzr
; ASM-ELF-NEXT:    ret
;
; ASM-DARWIN-LABEL: choose_disc_phi_placement:
; ASM-DARWIN:       ; %bb.0: ; %entry
; ASM-DARWIN-NEXT:    tst w0, #0x1
; ASM-DARWIN-NEXT:    csel x8, x2, x1, eq
; ASM-DARWIN-NEXT:    tbz w0, #0, LBB3_2
; ASM-DARWIN-NEXT:  ; %bb.1: ; %bb.user
; ASM-DARWIN-NEXT:    mov x17, x8
; ASM-DARWIN-NEXT:    movk x17, #1234, lsl #48
; ASM-DARWIN-NEXT:    pacia x3, x17
; ASM-DARWIN-NEXT:    mov x0, x3
; ASM-DARWIN-NEXT:    ret
; ASM-DARWIN-NEXT:  LBB3_2: ; %bb.ret0
; ASM-DARWIN-NEXT:    mov x0, #0 ; =0x0
; ASM-DARWIN-NEXT:    ret
entry:
  br i1 %cond, label %bb.blend.1, label %bb.blend.2
bb.blend.1:
  %disc.1 = call i64 @llvm.ptrauth.blend(i64 %addr.1, i64 1234)
  br label %bb.phi
bb.blend.2:
  %disc.2 = call i64 @llvm.ptrauth.blend(i64 %addr.2, i64 1234)
  br label %bb.phi
bb.phi:
  %disc = phi i64 [ %disc.1, %bb.blend.1 ], [ %disc.2, %bb.blend.2 ]
  br i1 %cond, label %bb.user, label %bb.ret0
bb.user:
  %result = call i64 @llvm.ptrauth.sign(i64 %ptr, i32 0, i64 %disc)
  ret i64 %result
bb.ret0:
  ret i64 0
}
